/**
 * Niral server — polyglot server blocks.
 *
 * `serverInfo()` answers: what language is this route's <server> block, what
 * does it export? `materialize()` writes non-JS server code to a stable temp
 * file for the language worker to load (rewritten when the source changes).
 */

import { readFileSync, statSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import { parse } from "../compiler/parser.js";
import { collectServerExports } from "../compiler/codegen.js";

export const LANG_EXT = { js: "js", python: "py", ruby: "rb", go: "go" };

const FRAMEWORK_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const infoCache = new Map(); // absPath → { mtimeMs, lang, code, exports }

/** Parse the <server> block of a .niral file (mtime-cached). null = no block. */
export function serverInfo(absPath) {
  if (!absPath.endsWith(".niral")) return null; // jsx/tsx components have no <server> block
  const mtimeMs = statSync(absPath).mtimeMs;
  const hit = infoCache.get(absPath);
  if (hit && hit.mtimeMs === mtimeMs) return hit.info;

  const ast = parse(readFileSync(absPath, "utf8"), absPath);
  let info = null;
  if (ast.server) {
    const lang = ast.server.attrs?.lang ?? "js";
    info = {
      lang,
      code: ast.server.code,
      exports: collectServerExports(ast.server.code, lang),
      auth: ast.server.attrs?.auth ?? null, // <server auth> / <server auth="role">
    };
  }
  infoCache.set(absPath, { mtimeMs, info });
  return info;
}

/**
 * Write non-JS server code to a stable temp file for its worker.
 * Returns { file, changed } — changed means the worker must be invalidated.
 *
 * Go is compiled, not eval'd: instead of a single file we materialize a
 * PACKAGE directory (go.mod + runner.go harness + generated registry.go +
 * the user's server.go) and the worker runs `go run <dir>`.
 */
export function materialize(absPath, info) {
  if (info.lang === "go") return materializeGo(absPath, info);
  const dir = join(tmpdir(), "niral-server-modules");
  mkdirSync(dir, { recursive: true });
  const name = createHash("sha256").update(absPath).digest("hex").slice(0, 16);
  const file = join(dir, `${name}.${LANG_EXT[info.lang] ?? info.lang}`);
  const current = existsSync(file) ? readFileSync(file, "utf8") : null;
  if (current === info.code) return { file, changed: false };
  writeFileSync(file, info.code);
  return { file, changed: current !== null };
}

function materializeGo(absPath, info) {
  const name = createHash("sha256").update(absPath).digest("hex").slice(0, 16);
  const dir = join(tmpdir(), "niral-server-modules", `go-${name}`);
  mkdirSync(dir, { recursive: true });

  const serverGo = `package main\n\n${info.code}\n`;
  const names = (info.exports ?? []).filter((n) => n !== "main" && n !== "init");
  const registryGo =
    "package main\n\n// GENERATED by niral — the dispatch registry for this server block.\nvar __fns = map[string]any{\n" +
    names.map((n) => `\t${JSON.stringify(n)}: ${n},`).join("\n") +
    "\n}\n";

  const serverFile = join(dir, "server.go");
  const current = existsSync(serverFile) ? readFileSync(serverFile, "utf8") : null;
  const registryFile = join(dir, "registry.go");
  const currentReg = existsSync(registryFile) ? readFileSync(registryFile, "utf8") : null;
  const runnerSrc = readFileSync(join(FRAMEWORK_DIR, "langs", "go", "runner.go"), "utf8");
  const runnerFile = join(dir, "runner.go");
  const currentRunner = existsSync(runnerFile) ? readFileSync(runnerFile, "utf8") : null;
  const bin = join(dir, "server.bin");
  if (current === serverGo && currentReg === registryGo && currentRunner === runnerSrc && existsSync(bin)) {
    return { file: bin, changed: false };
  }

  writeFileSync(join(dir, "go.mod"), "module niral_server\n\ngo 1.22\n");
  writeFileSync(runnerFile, runnerSrc);
  writeFileSync(registryFile, registryGo);
  writeFileSync(serverFile, serverGo);

  // compile HERE — the worker just execs the binary (fast start, and compile
  // errors surface with Go's real diagnostics instead of a dead worker)
  try {
    execFileSync("go", ["build", "-o", bin, "."], { cwd: dir, stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    if (e.code === "ENOENT") {
      throw new Error(`'go' not found — install Go to use <server lang="go">`);
    }
    const detail = e.stderr?.toString?.().trim() || e.message;
    throw new Error(`<server lang="go"> failed to compile:\n${detail}`);
  }
  return { file: bin, changed: current !== null };
}
